import './admin/adminAuth.test.js';
import './admin/adminRouter.test.js';
import './admin/adminPostViews.test.js';
import './admin/adminRepository.test.js';
import './admin/adminService.test.js';
import './admin/adminSql.test.js';
import './moderation/moderationSql.test.js';
import './config/env.test.js';
import './lib/passwordPolicy.test.js';
